apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-api
spec:
  template:
    spec:
      containers:
      - name: api-to-rds
        image: crisosilva88/api-to-rds:latest
        env:
        - name: RDS_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rds_host
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rds_username
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rds_password
      restartPolicy: Never